// svelte/src/App.svelte
<script>
	export let name 
	import Emoji from 'svelte-emoji'
	let count = 0
</script>

<main class="svelte-container">
	<h1><Emoji symbol="👋" />{' '}Hello {name || 'beautiful'}!</h1>
	<p>I am a <b>Svelte app</b> created with <code>svelte/template</code></p>
	<button on:click={() => count++}>
		<Emoji symbol="👍"/>{' '}
		<b>Like count: {count}</b>
	</button>
</main>

// vue/src/App.vue
<template>
  <main class="vue-container">
    <h1>Hello {{ name || 'beautiful' }}!</h1>
    <p>I am a <b>Vue app</b> created with <code>vite-app</code></p>
    <button @click="count++">
      <b>Like count: {{ count }}</b>
    </button>
  </main>
</template>

<script>
export default {
  name: "App",
  props: {
    name: String
  },
  data() {
    return {
      count: 0
    }
  }
};
</script>
